name: Build blogs from Trello Card

on:
  push:
    branches:
      - gh-pages
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and commit on same branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy env variable
        run: echo ${{ secrets.DOT_ENV }} >> .env
      - name: rm posts
        run: |
          cp ./scripts/rmposts.sh _posts/rmposts.sh
          chmod +x _posts/rmposts.sh
          cd _posts
          sh rmposts.sh
          rm rmposts.sh
          cd ..
      - name: Build posts
        run: |
          npm run hook
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
  